### ISSUE TITLE
Active Edge Table

### ISSUE THREAD

**Issue by morganherlocker** [mapbox/tile-cover#31]
The scanline will be faster under high vertex load given an AET index implementation.

>  the rasterizer maintains an active edge table(AET). Entries maintain sort links, X coordinates, gradients, and references to the polygons they bound. To rasterize the next scanline, the edges no longer relevant are removed; new edges from the current scanlines' Y-bucket are added, inserted sorted by X coordinate. The active edge table entries have X and other parameter information incremented. Active edge table entries are maintained in an X-sorted list by bubble sort, effecting a change when 2 edges cross. After updating edges, the active edge table is traversed in X order to emit only the visible spans, maintaining a Z-sorted active Span table, inserting and deleting the surfaces when edges are crossed.

**Comment by mourner** [comment]
Superseded by #69 since we don't need to calculate intersections anymore.
