### ISSUE TITLE
Expected behavior of min_zoom and max_zoom?

### ISSUE THREAD

**Issue by veltman** [mapbox/tile-cover#64]
I'm a little unclear on how a case with multiple zoom levels is supposed to work.

```js
var cover = require("tile-cover");

var geom = {
  "type": "Polygon",
  "coordinates": [
    [
      [
        -74.03549194335938,
        40.66918118282895
      ],
      [
        -74.03549194335938,
        40.84913799774759
      ],
      [
        -73.86245727539062,
        40.84913799774759
      ],
      [
        -73.86245727539062,
        40.66918118282895
      ],
      [
        -74.03549194335938,
        40.66918118282895
      ]
    ]
  ]
};

console.log(cover.tiles(geom,{min_zoom: 14, max_zoom: 14}).length); // 108 tiles
console.log(cover.tiles(geom,{min_zoom: 15, max_zoom: 15}).length); // 368 tiles
console.log(cover.tiles(geom,{min_zoom: 14, max_zoom: 15}).length); // 137 tiles??
```

I would expect that when `min_zoom` is less than `max_zoom`, the array I get back would be the combination of the array for each zoom level in the range.  So in the above example, I would assume that the third statement would produce 476 tiles (108 + 368).  Is that not what's supposed to happen?

**Comment by morganherlocker** [comment]
When min and max are equal, the cover is simply a collection of tiles at one zoom level. Setting a lower min_zoom than max_zoom will make the algorithm merge tiles when possible, up to the min_zoom. Here is an example of this in practice:

![](https://camo.githubusercontent.com/457c6b6ae74500bf5a81407feb9c2b5b4fa7849b/68747470733a2f2f646c2e64726f70626f782e636f6d2f732f3438636a3136667674386e7968336f2f53637265656e73686f74253230323031342d30382d303625323031332e33342e31322e706e67)

The idea here is to deliver the absolute minimum number of indexes needed to cover an entire shape. If you are looking for multiple unmerged zoom levels that stack on top of one another, you could do something like:

```js
cover.tiles(geom,{min_zoom: 14, max_zoom: 14}).concat(
cover.tiles(geom,{min_zoom: 15, max_zoom: 15}))
```

**Comment by veltman** [comment]
Got it, thanks for the clarification!
