### ISSUE TITLE
Features that cross the dateline

### ISSUE THREAD

**Issue by rclark** [mapbox/tile-cover#65]
If you calculate the tile-cover for a feature that with X coordinates > 180, you can end up with bogus tile coordinates, for example `[260,52,8]`. Would it be worth a PR that tries to coerce to coordinates within the right limits (in this example, `[4,52,8]`)? Or is it better to handle this outcome in the downstream app?

cc @morganherlocker

**Comment by mourner** [comment]
I would expect this to be handled on the downstream app, since the wrapping is lossy (e.g. you can end up with coordinates you don't know what to do with).

**Comment by rclark** [comment]
:+1: to managing this downstream.
