### ISSUE TITLE
FATAL ERROR: invalid table size Allocation failed - process out of memory

### ISSUE THREAD

**Issue by jczaplew** [mapbox/tile-cover#71]
I've run into an error where [this polygon](https://gist.github.com/jczaplew/0ed7daec6308ccfcd6f1) produces the following error:

````
FATAL ERROR: invalid table size Allocation failed - process out of memory
Abort trap: 6
````

while running `cover.tiles(*problematic polygon*, {min_zoom: 0, max_zoom: 1})`. I have run other similar polygons through tile-cover without any issues.

**Comment by jczaplew** [comment]
It seems to possibly a problem with wrapping the poles, as clipping the polygon to 85N seemed to resolve the problem.

**Comment by mourner** [comment]
Yeah, something weird going on definitely. Need to take a look.

**Comment by mourner** [comment]
Probably the same issue as #66.

**Comment by derhuerst** [comment]
I'm getting this error when I pass a way to large bounding box. It should probably throw an error, so that consuming libraries can handle this case. right now the whole process just freezes and crashes, potentially user-facing or even in the browser.

**Comment by Harsh-Singh12** [comment]
I am creting contact app by downloading all modules and files .. facing the same issue:-invalid table size Allocation failed-javascript out of memory.
