### ISSUE TITLE
Output spec compliant

### ISSUE THREAD

**Issue by maning** [mapbox/tile-cover#82]
Running my output from tile-cover to `geojsonhint`, I get the following error

```
30637:1  warning  Polygons and MultiPolygons should follow the right-hand rule
30638:1  warning  Polygons and MultiPolygons should follow the right-hand rule
```

I fixed it with [geojson-rewind](https://github.com/mapbox/geojson-rewind), but a spec compliant output is better.

**Comment by mourner** [comment]
The conversion actually happens in `tilebelt` (https://github.com/mapbox/tile-cover/blob/master/index.js#L25), so you should probably open an issue (or a PR?) there instead.

**Comment by maning** [comment]
Thanks! Opened one: https://github.com/mapbox/tilebelt/issues/35
